In [1]:
import sys
if ".." not in sys.path:
    sys.path.append("..")
from franke_wolfe import fw_optimize
import fw_draw
import numpy as np
import math

In [2]:
bounds = [(0, 1), (0, 4)]
(cx, cy) = (4, 2)
cx = 4
cy = 1.66666666
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 5
options = {}
perturb = True
runner = fw_optimize.FrankWolfe(objective_2d, bounds=bounds, options=options, iteration_limit=lm)
if perturb:
    A_ub = [[-0.1, -1]]
    b_ub = [-0.1]
    runner = fw_optimize.FrankWolfe(objective_2d, 
                                    A_ub = A_ub,
                                    b_ub = b_ub,
                                    bounds=bounds, 
                                    options=options, 
                                    iteration_limit=lm)
#runner.verbose = True
runner.vertex_ratio = 0.66
runner.blend = False
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "red")
if perturb:
    D.line(None, 0, 0.1, 1, 0, "magenta")
D = ill.draw()
D.embed()

<IPython.core.display.Javascript object>

In [3]:

(cx, cy) = (1, 1)
cx = 0
cy = 7.111
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 12
options = {}
perturb = True

A_ub = [
    [-4.0/7, 1],
    [-1.0/5, -1],
    [5.0/2, -1]
]
b_ub = [3, -3, 21.0/2]
runner = fw_optimize.FrankWolfe(objective_2d, 
                                A_ub = A_ub,
                                b_ub = b_ub,
                                options=options, 
                                iteration_limit=lm)
runner.vertex_ratio = None
runner.blend = True
runner.vertex_ratio = None
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
ill.location((8, 8))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "cyan")

D.line(None, 0,3,5,2, "magenta",5)
D.line(None, 0,3,7,7, "magenta",5)
D.line(None, 7,7,5,2, "magenta",5)

D = ill.draw()
D.embed()

In [4]:

(cx, cy) = (1, 1)
cx = 3
cy = 3
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 6
options = {}
perturb = True

A_ub = [
    [-4.0/7, 1],
    [-1.0/5, -1],
    [5.0/2, -1]
]
b_ub = [3, -3, 21.0/2]
bounds = [(1,6), (1,6)]
runner = fw_optimize.FrankWolfe(objective_2d, 
                                A_ub = A_ub,
                                b_ub = b_ub,
                                options=options, 
                                bounds=bounds,
                                iteration_limit=lm)
runner.blend = True
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
ill.location((8, 8))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.rect(None, 1, 1, 5, 5, "#aaaaff")
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "cyan")

D.line(None, 0,3,5,2, "magenta",5)
D.line(None, 0,3,7,7, "magenta",5)
D.line(None, 7,7,5,2, "magenta",5)

D = ill.draw()
D.embed()

In [5]:
ill.callback_args[-1]

(            status: 1
            runner: <franke_wolfe.fw_optimize.FrankWolfe object at 0x10cb5a550>
            vertex: array([ 6. ,  4.5])
           g_count: 7
           message: 'Did not converge after 6 iterations.'
          estimate: array([ 2.85225684,  3.03791344])
               nit: 5
     next_estimate: array([ 2.95640004,  3.07421752])
             slack: array([ 1.92857143,  2.7       ,  0.        ,  1.5       ,  0.        ,
        3.5       ,  0.        ])
           success: False
 convergence_value: 0.81924960428573201
             blend: array([ 2.95638393,  3.0742014 ])
         iteration: 5
     scalar_result:    start: array([ 2.95638393,  3.0742014 ])
 message: 'improvement found'
     end: array([ 4.01204819,  4.13080895])
 success: True
       x: array([ 2.95640004,  3.07421752])
               fun: 0.007409197366034374
                 x: array([ 2.95640004,  3.07421752])
         tolerance: 1e-12
           f_count: 73,
 False,
 array([ 2.85225684,  3.0379

In [6]:

(cx, cy) = (1, 1)
cx = 0.666
cy = -0.1
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 12
options = {}
perturb = True

A_ub = [
    [-3.0, 1],
    [-3.0, -1],
    [1, 0]
]
b_ub = [0, 0, 1]
bounds = [(None, None), (None, None)]
runner = fw_optimize.FrankWolfe(objective_2d, 
                                A_ub = A_ub,
                                b_ub = b_ub,
                                options=options, 
                                bounds=bounds,
                                iteration_limit=lm)
runner.blend = False
#runner.vertex_ratio = None
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
ill.location((4,4))
ill.location((4,-4))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "cyan")

D.line(None, 0,0,1,3, "magenta",5)
D.line(None, 0,0,1,-3, "magenta",5)
D.line(None, 1,-3,1,3, "magenta",5)

D = ill.draw()
D.embed()

In [7]:
ill.callback_args[-1]

(            status: 1
            runner: <franke_wolfe.fw_optimize.FrankWolfe object at 0x10ee532d0>
            vertex: array([ 1., -3.])
           g_count: 13
           message: 'Did not converge after 12 iterations.'
          estimate: array([ 0.6776655 , -0.09392388])
               nit: 11
             slack: array([ 6.,  0.,  0.])
           success: False
 convergence_value: 0.027794957041962248
             blend: array([ 0.67503445, -0.09555592])
         iteration: 11
     scalar_result:        x: array([ 0.67829506, -0.09959981])
 success: True
               fun: 0.00015132857335936167
                 x: array([ 0.67829506, -0.09959981])
         tolerance: 1e-12
           f_count: 148,
 False,
 array([ 0.6776655 , -0.09392388]),
 array([ 0.023331  ,  0.01215224]),
 array([ 1., -3.]),
 array([ 0.67829506, -0.09959981]),
 array([ 0.67503445, -0.09555592]))

In [8]:
a = np.array(A_ub)
b = np.array(b_ub)

In [ ]:
b - a.dot((3,0))

In [ ]:
runner.objective(a)

In [ ]:
runner.objective((b[0], b[1]))

In [11]:
a.T

array([[-3., -3.,  1.],
       [ 1., -1.,  0.]])

In [ ]:
rs.test = "whatever"

In [ ]:
rs

In [31]:
xc = 1
yc = -4

def algebraic(x, y):
    return (x - xc) ** 2 + (y - yc) ** 2

def matrices(x, y):
    C = np.array([[1, 0], [0, 1]])
    d = -2 * np.array([xc, yc])
    xy = np.array([x, y])
    Cpart = xy.T.dot(C).dot(xy)
    Dpart = d.T.dot(xy)
    print Cpart, Dpart
    return Cpart + Dpart + xc**2 + yc**2

In [32]:
algebraic(1, -4)

0

In [33]:
matrices(1, -4)

17 -34


0

In [36]:
xo = 3
yo = 6
xs = 0.4
ys = 1.2
for i in range(3):
    for j in range(3):
        x = xo + xs * i
        y = yo + ys * j
        a = algebraic(x,y)
        m = matrices(x,y)
        print a, m
        assert abs(a-m) < 1e-10

45.0 42.0
104.0 104.0
60.84 51.6
129.44 129.44
79.56 61.2
157.76 157.76
47.56 41.2
105.76 105.76
63.4 50.8
131.2 131.2
82.12 60.4
159.52 159.52
50.44 40.4
107.84 107.84
66.28 50.0
133.28 133.28
85.0 59.6
161.6 161.6


In [5]:
ill.illustrate_steps()

illustrating 5 steps.


In [17]:
i = np.identity(3)
v = np.array([1,2,3])
v.reshape((3,1))

array([[1],
       [2],
       [3]])

In [18]:

np.hstack([np.identity(3), v.reshape(3,1)])

array([[ 1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  2.],
       [ 0.,  0.,  1.,  3.]])

In [20]:
np.hstack([[1,2,3], [4]])

array([1, 2, 3, 4])