In [1]:
import sys
if ".." not in sys.path:
    sys.path.append("..")
from franke_wolfe import fw_vector
import fw_draw
import numpy as np
import math

In [2]:
bounds = [(0, 1), (0, 4)]
(cx, cy) = (4, 2)
cx = 4
cy = 1.66666666
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 5
options = {}
perturb = False
runner = fw_vector.FrankeWolfeVectorized(objective_2d, bounds=bounds, options=options, iteration_limit=lm)
if perturb:
    A_ub = [[-0.1, -1]]
    b_ub = [-0.1]
    runner = fw_optimize.FrankWolfe(objective_2d, 
                                    A_ub = A_ub,
                                    b_ub = b_ub,
                                    bounds=bounds, 
                                    options=options, 
                                    iteration_limit=lm)
runner.verbose = True
runner.vertex_ratio = 0.66
runner.blend = False
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "red")
if perturb:
    D.line(None, 0, 0.1, 1, 0, "magenta")
D = ill.draw()
D.embed()

fallback to standard linear approximation.
optimizing array([ 0.,  0.])
optimized at array([ 0.,  0.])
fallback to standard linear approximation.
optimizing array([-8.00000066, -3.33333361])
optimized at array([ 1.,  4.])
fallback to standard linear approximation.
optimizing array([-6.0000005 ,  4.66666705])
optimized at array([ 1.,  0.])
fallback to standard linear approximation.
optimizing array([-6.0000005 , -3.33333361])
optimized at array([ 1.,  4.])
feasible point array([ 1.,  0.])
vector optimizing: array([-6.0000005 , -3.33333361,  0.        ])
bounds [(0, 1), (0, 4), (None, None)]
no progress in vector optimization: fallback to standard.
optimizing array([-6.0000005 , -3.33333361])
optimized at array([ 1.,  4.])
next estimate array([ 1.,  2.])
vector optimizing: array([-6.0000005 ,  0.66666672,  0.        ])
bounds [(0, 1), (0, 4), (None, None)]
no progress in vector optimization: fallback to standard.
optimizing array([-6.0000005 ,  0.66666672])
optimized at array([ 1.,  0.])

<IPython.core.display.Javascript object>

In [ ]:
debug

In [5]:
(cx, cy) = (1, 1)
cx = 3
cy = 3
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 12
options = {}
perturb = True

A_ub = [
    [-4.0/7, 1],
    [-1.0/5, -1],
    [5.0/2, -1]
]
b_ub = [3, -3, 21.0/2]
runner = fw_vector.FrankeWolfeVectorized(objective_2d, 
                                A_ub = A_ub,
                                b_ub = b_ub,
                                options=options, 
                                iteration_limit=lm)
runner.verbose = True
runner.vertex_ratio = None
runner.blend = True
runner.vertex_ratio = None
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
ill.location((8, 8))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "cyan")

D.line(None, 0,3,5,2, "magenta",5)
D.line(None, 0,3,7,7, "magenta",5)
D.line(None, 7,7,5,2, "magenta",5)

D = ill.draw()
D.embed()

fallback to standard linear approximation.
optimizing array([ 0.,  0.])
optimized at array([ 0.,  3.])
fallback to standard linear approximation.
optimizing array([-6.0000005,  0.       ])
optimized at array([ 7.,  7.])
feasible point array([ 0.,  3.])
vector optimizing: array([-6.0000005,  0.       ,  0.       ])
bounds None
next estimate array([ 2.7,  3. ])
vector optimizing: array([-0.60000005,  0.        ,  0.        ])
bounds None
next estimate array([ 3.51325301,  3.        ])
vector optimizing: array([ 1.0265061,  0.       ,  0.       ])
bounds None
next estimate array([ 2.76307951,  3.        ])
vector optimizing: array([-0.47384104,  0.        ,  0.        ])
bounds None
next estimate array([ 3.09270191,  3.        ])
vector optimizing: array([ 0.18540383,  0.        ,  0.        ])
bounds None
next estimate array([ 2.96162796,  3.        ])
vector optimizing: array([-0.07674409,  0.        ,  0.        ])
bounds None
next estimate array([ 3.03783579,  3.        ])
vector opti

In [ ]:

(cx, cy) = (1, 1)
cx = 3
cy = 3
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 6
options = {}
perturb = True

A_ub = [
    [-4.0/7, 1],
    [-1.0/5, -1],
    [5.0/2, -1]
]
b_ub = [3, -3, 21.0/2]
bounds = [(1,6), (1,6)]
runner = fw_optimize.FrankWolfe(objective_2d, 
                                A_ub = A_ub,
                                b_ub = b_ub,
                                options=options, 
                                bounds=bounds,
                                iteration_limit=lm)
runner.blend = True
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
ill.location((8, 8))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.rect(None, 1, 1, 5, 5, "#aaaaff")
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "cyan")

D.line(None, 0,3,5,2, "magenta",5)
D.line(None, 0,3,7,7, "magenta",5)
D.line(None, 7,7,5,2, "magenta",5)

D = ill.draw()
D.embed()

In [ ]:
ill.callback_args[-1]

In [ ]:

(cx, cy) = (1, 1)
cx = 0.666
cy = -0.1
def objective_2d(a):
    [x, y] = a
    return (x - cx) ** 2 + (y - cy) ** 2
lm = 12
options = {}
perturb = True

A_ub = [
    [-3.0, 1],
    [-3.0, -1],
    [1, 0]
]
b_ub = [0, 0, 1]
bounds = [(None, None), (None, None)]
runner = fw_optimize.FrankWolfe(objective_2d, 
                                A_ub = A_ub,
                                b_ub = b_ub,
                                options=options, 
                                bounds=bounds,
                                iteration_limit=lm)
runner.blend = False
#runner.vertex_ratio = None
ill = fw_draw.Illustration(runner)
ill.location((cx, cy))
ill.location((0, 0))
ill.location((4,4))
ill.location((4,-4))
D = ill.get_canvas()
radius = 0.01 * np.max(ill.maxes - ill.mins)
D.circle(None, cx, cy, (ill.maxes[0]-ill.mins[0])*0.05, "cyan")

D.line(None, 0,0,1,3, "magenta",5)
D.line(None, 0,0,1,-3, "magenta",5)
D.line(None, 1,-3,1,3, "magenta",5)

D = ill.draw()
D.embed()

In [ ]:
ill.callback_args[-1]

In [ ]:
a = np.array(A_ub)
b = np.array(b_ub)

In [ ]:
b - a.dot((3,0))

In [ ]:
runner.objective(a)

In [ ]:
runner.objective((b[0], b[1]))

In [ ]:
a.T

In [ ]:
rs.test = "whatever"

In [ ]:
rs

In [ ]:
xc = 1
yc = -4

def algebraic(x, y):
    return (x - xc) ** 2 + (y - yc) ** 2

def matrices(x, y):
    C = np.array([[1, 0], [0, 1]])
    d = -2 * np.array([xc, yc])
    xy = np.array([x, y])
    Cpart = xy.T.dot(C).dot(xy)
    Dpart = d.T.dot(xy)
    print Cpart, Dpart
    return Cpart + Dpart + xc**2 + yc**2

In [ ]:
algebraic(1, -4)

In [ ]:
matrices(1, -4)

In [ ]:
xo = 3
yo = 6
xs = 0.4
ys = 1.2
for i in range(3):
    for j in range(3):
        x = xo + xs * i
        y = yo + ys * j
        a = algebraic(x,y)
        m = matrices(x,y)
        print a, m
        assert abs(a-m) < 1e-10

In [ ]:
ill.illustrate_steps()

In [ ]:
i = np.identity(3)
v = np.array([1,2,3])
v.reshape((3,1))

In [ ]:

np.hstack([np.identity(3), v.reshape(3,1)])

In [ ]:
np.hstack([[1,2,3], [4]])

In [6]:
ill.callback_args

[(            status: 0
       augmented_x: array([ 5.4       ,  3.        ,  0.89999993])
            runner: <franke_wolfe.fw_vector.FrankeWolfeVectorized object at 0x10c258590>
            vertex: array([ 5.4,  3. ])
           message: 'Optimization terminated successfully.'
          estimate: array([ 0.,  3.])
               nit: 4
     next_estimate: array([ 2.7,  3. ])
             slack: array([ 3.08571429,  1.08      ,  0.        ])
           success: True
 convergence_value: 32.40000268078802
             blend: array([ 0.,  3.])
         iteration: 0
     scalar_result:    start: array([ 0.,  3.])
 message: 'improvement found'
     end: array([ 5.4,  3. ])
 success: True
       x: array([ 2.7,  3. ])
               fun: -32.400002680788027
                 x: array([ 5.4,  3. ])
         tolerance: 1e-12,
  False,
  array([ 0.,  3.]),
  array([-6.0000005,  0.       ]),
  array([ 5.4,  3. ]),
  array([ 2.7,  3. ]),
  array([ 0.,  3.])),
 (            status: 0
       augmen